### ISSUE TITLE
OutOfMemoryError:Java heap space

### ISSUE THREAD

**Issue by idejie** [OpenIE-HelperCodes/OpenIEDemo1#2]
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.lang.reflect.Array.newArray(Native Method)
	at java.lang.reflect.Array.newInstance(Array.java:75)
	at java.io.ObjectInputStream.readArray(ObjectInputStream.java:1883)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1529)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2231)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2155)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2013)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1535)
	at java.io.ObjectInputStream.readArray(ObjectInputStream.java:1919)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1529)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:422)
	at com.clearnlp.component.AbstractStatisticalComponent.loadDefault(AbstractStatisticalComponent.java:200)
	at com.clearnlp.component.pos.AbstractPOSTagger.load(AbstractPOSTagger.java:138)
	at com.clearnlp.component.AbstractStatisticalComponent.<init>(AbstractStatisticalComponent.java:120)
	at com.clearnlp.component.pos.AbstractPOSTagger.<init>(AbstractPOSTagger.java:124)
	at com.clearnlp.component.pos.EnglishPOSTagger.<init>(EnglishPOSTagger.java:91)
	at com.clearnlp.nlp.NLPGetter.getPOSTagger(NLPGetter.java:191)
	at com.clearnlp.nlp.NLPGetter.getComponent(NLPGetter.java:159)
	at com.clearnlp.nlp.NLPGetter.getComponent(NLPGetter.java:147)
	at edu.knowitall.tool.postag.ClearPostagger.<init>(ClearPostagger.scala:18)
	at edu.knowitall.openie.OpenIE.<init>(OpenIE.scala:33)
	at OpenIE.RunMe.main(RunMe.java:26)

**Comment by harrysethi** [comment]
OpenIE needs more memory, can you try with "sbt -J-Xmx5g clean compile assembly" instead of "sbt -J-Xmx2700M clean compile assembly"
